package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"log/slog"
	"loggenerator/filter"
	"loggenerator/model"
	"os"
)

func main() {
	inFile := flag.String("in", "parsed_logs.json", "Input JSON file generated by log_parser (required)")
	level := flag.String("level", "", "Comma separated list of log levels")
	component := flag.String("component", "", "Comma separated list of components")
	host := flag.String("host", "", "Comma separated list of hosts")
	reqID := flag.String("reqID", "", "Comma separated list of requestIDs")
	startTimeString := flag.String("after", "", "Filter by start time [2006-01-02 15:04:05]")
	endTimeString := flag.String("before", "", "Filter by end time [2006-01-02 15:04:05]")
	flag.Parse()

	file, err := os.Open(*inFile)
	if err != nil {
		slog.Error("Failed to open JSON file", "error", err)
	}
	defer file.Close()

	var logStore model.LogStore
	if err := json.NewDecoder(file).Decode(&logStore); err != nil {
		slog.Error("Error decoding JSON", "error", err)
	}

	levels := split(*level)
	components := split(*component)
	hosts := split(*host)
	reqIDs := split(*reqID)

	startTime := parseTimeFlag(*startTimeString)
	endTime := parseTimeFlag(*endTimeString)

	filteredLogs := filter.FilterLogs(logStore, levels, components, hosts, reqIDs, startTime, endTime)
	fmt.Printf("Found %d matching entries\n", len(filteredLogs))
	for _, entry := range filteredLogs {
		fmt.Println(entry.Raw)
	}
}
